In [1]:
import numpy as np

In [2]:
x = np.array([2,3,4,6,7,7,12,34])

In [3]:
print(x)

[ 2  3  4  6  7  7 12 34]


In [4]:
x = np.array([[4,5,6,6,2,4],[5,4,7,9,2,1],[1,6,8,2,3]])

In [5]:
print(x)

[[4, 5, 6, 6, 2, 4] [5, 4, 7, 9, 2, 1] [1, 6, 8, 2, 3]]


In [6]:
x = np.random.random((4,4))

In [7]:
x

array([[ 0.69852246,  0.24701457,  0.5376029 ,  0.41757873],
       [ 0.61480024,  0.15293951,  0.65412732,  0.59180774],
       [ 0.02588502,  0.60820222,  0.57236549,  0.25574262],
       [ 0.79623601,  0.13455018,  0.68201031,  0.24064623]])

In [8]:
x[0]

array([ 0.69852246,  0.24701457,  0.5376029 ,  0.41757873])

In [9]:
x[0:2]

array([[ 0.69852246,  0.24701457,  0.5376029 ,  0.41757873],
       [ 0.61480024,  0.15293951,  0.65412732,  0.59180774]])

In [10]:
x[0:2, 0:2]

array([[ 0.69852246,  0.24701457],
       [ 0.61480024,  0.15293951]])